import type { Metadata } from 'next'
import MyClerkProvider from '@/components/clerkProvider'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import QueryProvider from "@/components/QueryProvider" // <-- import the new provider
import Navbar from '@/components/Navbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Coffee shop app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <QueryProvider>
      <MyClerkProvider>
        <html lang="en" className="dark">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navbar />
            {children}
          </body>
        </html>
      </MyClerkProvider>
    </QueryProvider>
  )
}